trigger:
- master

jobs:
- template: azure/azure-linux-macos.yml
  parameters:
    name: macOS
    vmImage: macOS-latest
    matrix:
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'

- template: azure/azure-linux-macos.yml
  parameters:
    name: Linux
    vmImage: ubuntu-latest
    matrix:
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
