[build-system]
requires = ["setuptools", "wheel"]

[tool.pytest]
addopts = -ra --cov=mutatest --cov-report=html

[tool.black]
line-length = 100
py36 = true
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
